- Pentype: PenUp
  Position:
  - 0.2
  - 0.0
  - 0.3978
- Pentype: PenUp
  Position:
  - 0.2
  - 0.0
  - 0.3978
- Pentype: PenDown
  Position:
  - 0.2
  - -0.1
  - 0.35000000000000003
- Pentype: PenDown
  Position:
  - 0.2
  - -0.1
  - 0.4
- Pentype: PenDown
  Position:
  - 0.2
  - -0.05
  - 0.4
- Pentype: PenDown
  Position:
  - 0.2
  - -0.1
  - 0.4
- Pentype: PenDown
  Position:
  - 0.2
  - -0.1
  - 0.45
- Pentype: PenUp
  Position:
  - 0.2
  - -0.05
  - 0.45
- Pentype: PenDown
  Position:
  - 0.2
  - 0.0
  - 0.45
- Pentype: PenUp
  Position:
  - 0.2
  - 0.0
  - 0.35000000000000003
- Pentype: PenDown
  Position:
  - 0.2
  - 0.05
  - 0.45
- Pentype: PenDown
  Position:
  - 0.2
  - 0.1
  - 0.45
- Pentype: PenDown
  Position:
  - 0.2
  - 0.05
  - 0.4
- Pentype: PenDown
  Position:
  - 0.2
  - 0.1
  - 0.35000000000000003
- Pentype: PenDown
  Position:
  - 0.2
  - 0.05
  - 0.35000000000000003
- Pentype: PenUp
  Position:
  - 0.2
  - 0.05
  - 0.45
- Pentype: PenDown
  Position:
  - 0.2
  - 0.15000000000000002
  - 0.45
- Pentype: PenDown
  Position:
  - 0.2
  - 0.2
  - 0.45
- Pentype: PenDown
  Position:
  - 0.2
  - 0.2
  - 0.35000000000000003
- Pentype: PenDown
  Position:
  - 0.2
  - 0.15000000000000002
  - 0.35000000000000003
- Pentype: PenUp
  Position:
  - 0.2
  - 0.15000000000000002
  - 0.45
- Pentype: PenUp
  Position:
  - 0.2
  - -0.15000000000000002
  - 0.45
